# Generated by Django 3.2.9 on 2021-11-13 19:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20211113_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_state', models.CharField(choices=[('YES', 'Bem'), ('NO', 'Não muito bem')], max_length=13, verbose_name='Estado de Saúde')),
                ('prognostic', models.CharField(max_length=2000, verbose_name='Prognósticos')),
                ('create_at', models.DateTimeField(default=datetime.datetime(2021, 11, 13, 16, 27, 14, 345092), verbose_name='Data de Criação')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile', verbose_name='Usuário')),
            ],
        ),
    ]
