# Generated by Django 3.2.9 on 2021-11-23 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_condition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthcondition',
            options={'verbose_name': 'Condição de Saúde', 'verbose_name_plural': 'Condições de Saúde'},
        ),
        migrations.AlterField(
            model_name='healthcondition',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 2, 57, 22, 701810), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='healthcondition',
            name='prognostic',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Prognósticos'),
        ),
    ]
