# Generated by Django 3.2.9 on 2021-11-27 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prognostic', '0002_alter_prognostic_options'),
        ('health_condition', '0002_auto_20211123_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcondition',
            name='prognostic_id',
            field=models.ManyToManyField(blank=True, to='prognostic.Prognostic', verbose_name='Prognósticos'),
        ),
        migrations.AlterField(
            model_name='healthcondition',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 4, 33, 11, 783384), verbose_name='Data de Criação'),
        ),
    ]
