# Generated by Django 3.2.9 on 2021-11-27 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_condition', '0003_auto_20211127_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcondition',
            name='prognostic',
        ),
        migrations.AlterField(
            model_name='healthcondition',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 4, 39, 46, 503899), verbose_name='Data de Criação'),
        ),
    ]
