# Generated by Django 3.2.9 on 2021-12-02 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_condition', '0004_auto_20211127_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcondition',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 21, 21, 28, 488518), verbose_name='Data de Criação'),
        ),
    ]
