# Generated by Django 3.2.9 on 2021-11-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AddField(
            model_name='sector',
            name='initial',
            field=models.CharField(default='', max_length=5, verbose_name='Sigla'),
            preserve_default=False,
        ),
    ]
