# Generated by Django 3.2.9 on 2021-11-25 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_dailyquantitybad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleQuantityBadLastFiveDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reference', models.DateField(default=datetime.date(2021, 11, 25), verbose_name='Data Referência')),
                ('result_report', models.TextField(blank=True, null=True, verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Quantidade de Pessoas que Respoderam "Não muito bem" nos Últimos 5 Dias',
                'verbose_name_plural': 'Quantidades de Pessoas que Respoderam "Não muito bem" nos Últimos 5 Dias',
            },
        ),
    ]
