# Generated by Django 3.2.9 on 2021-11-25 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_peoplequantitybadlastfivedays'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuantityBySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField(verbose_name='Data Inicial')),
                ('end_date', models.DateField(verbose_name='Data Final')),
                ('result_report', models.TextField(blank=True, null=True, verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Quantidade Diária por Setor',
                'verbose_name_plural': 'Quantidades Diárias por Setor',
            },
        ),
        migrations.AlterField(
            model_name='peoplequantitybadlastfivedays',
            name='date_reference',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Referência'),
        ),
    ]
