# Generated by Django 3.2.9 on 2021-11-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20211125_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuantityBadBySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField(verbose_name='Data Inicial')),
                ('end_date', models.DateField(verbose_name='Data Final')),
                ('result_report', models.TextField(blank=True, null=True, verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Quantidade Diária "Não muito bem" por Setor',
                'verbose_name_plural': 'Quantidades Diárias "Não muito bem" por Setor',
            },
        ),
        migrations.AlterModelOptions(
            name='peoplequantitybadlastfivedays',
            options={'verbose_name': 'Quantidade de Pessoas "Não muito bem" nos Últimos 5 Dias', 'verbose_name_plural': 'Quantidades de Pessoas "Não muito bem" nos Últimos 5 Dias'},
        ),
    ]
