# Generated by Django 3.2.9 on 2021-11-13 19:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0001_initial'),
        ('user', '0002_auto_20211113_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sector_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sector.sector', verbose_name='Setor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 16, 29, 6, 832607), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 16, 29, 6, 832634), verbose_name='Data da Última Atualização'),
        ),
    ]
