# Generated by Django 3.2.9 on 2021-11-13 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211113_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofilefile',
            options={'verbose_name': 'Carregamento de Perfil de Usuário', 'verbose_name_plural': 'Carregamentos de Perfil de Usuário'},
        ),
        migrations.AddField(
            model_name='userprofilefile',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 17, 47, 11, 144632), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 17, 47, 11, 143787), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 17, 47, 11, 143814), verbose_name='Data da Última Atualização'),
        ),
        migrations.AlterField(
            model_name='userprofilefile',
            name='import_file',
            field=models.FileField(upload_to='uploads/', verbose_name='Arquivo de Importação'),
        ),
    ]
