# Generated by Django 3.2.9 on 2021-11-13 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20211113_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileFileSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('user_type', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=200)),
                ('birthdate', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 20, 1, 16, 386449), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 20, 1, 16, 386502), verbose_name='Data da Última Atualização'),
        ),
        migrations.AlterField(
            model_name='userprofilefile',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 20, 1, 16, 388111), verbose_name='Data de Criação'),
        ),
    ]
