# Generated by Django 3.2.9 on 2021-11-19 04:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_auto_20211113_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 1, 27, 7, 712459), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 1, 27, 7, 712491), verbose_name='Data da Última Atualização'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='userprofilefile',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 1, 27, 7, 713254), verbose_name='Data de Criação'),
        ),
    ]
