# Generated by Django 3.2.9 on 2021-11-19 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20211119_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_user',
            field=models.CharField(default='', max_length=20, verbose_name='Identificação do Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 1, 30, 58, 706233), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 1, 30, 58, 706263), verbose_name='Data da Última Atualização'),
        ),
        migrations.AlterField(
            model_name='userprofilefile',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 1, 30, 58, 707125), verbose_name='Data de Criação'),
        ),
    ]
