# Generated by Django 3.2.9 on 2021-11-19 05:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_auto_20211119_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 2, 10, 49, 569889), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 2, 10, 49, 569917), verbose_name='Data da Última Atualização'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Estudante', 'Estudante'), ('Professor', 'Professor'), ('Funcionario', 'Funcionario'), ('RH', 'Recursos Humanos')], max_length=20, verbose_name='Tipo de Usuário'),
        ),
        migrations.AlterField(
            model_name='userprofilefile',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 2, 10, 49, 570856), verbose_name='Data de Criação'),
        ),
        migrations.CreateModel(
            name='UserPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200, verbose_name='Senha')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
