# Generated by Django 3.2.9 on 2021-11-28 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20211127_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilefile',
            name='example_file',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 15, 10, 43, 822523), editable=False, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 15, 10, 43, 822554), editable=False, verbose_name='Data da Última Atualização'),
        ),
        migrations.AlterField(
            model_name='userprofilefile',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 15, 10, 43, 824102), verbose_name='Data de Criação'),
        ),
    ]
