# Generated by Django 3.2.9 on 2021-11-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prognostic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prognostic',
            options={'verbose_name': 'Prognóstico', 'verbose_name_plural': 'Prognósticos'},
        ),
    ]
